---

R1:
  hostname: LA-DC-SRX-FW-PRY
  groups:
      - junos

# R2:
#   hostname: NYC-DC-SRX-FW
#   groups:
#       - junos

# R3:
#   hostname: AMS-DC-SRX-FW
#   groups:
#       - junos

# R4:
#   hostname: LA-DC-SRX-FW-PRY
#   groups:
#       - junos